///////////////////////////////////////////////////////////////////////////////
//
//  Copyright 2018-2026 Robonomics Network <research@robonomics.network>
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
///////////////////////////////////////////////////////////////////////////////
//! Canonical Connectivity Protocol layer.
//!
//! The wire types are generated (and committed) from the vendored `.proto`
//! definitions; see [`generated`]. Everything else in this module builds the
//! transport-neutral abstractions the pipeline operates on.

/// Generated Connectivity Protocol wire types.
///
/// Produced by `prost-build` from the vendored `.proto` files under
/// `src/protobufs/` (see `build.rs`) and committed to the repository; do not edit by hand.
/// Regenerate with `cargo build -p edge --features gen && cargo fmt`.
pub mod generated {
    #![allow(missing_docs)]
    #![allow(clippy::all)]
    #![allow(rustdoc::all)]

    /// `crypto.v1` protobuf package.
    pub mod crypto {
        /// `crypto.v1` protobuf package.
        pub mod v1 {
            include!("generated/crypto.v1.rs");
        }
    }

    /// `sensor.v1` protobuf package: per-device measurement payloads.
    pub mod sensor {
        /// `sensor.v1` protobuf package.
        pub mod v1 {
            include!("generated/sensor.v1.rs");
        }
    }

    /// `device.v1` protobuf package: urban/insight board sensor groupings.
    pub mod device {
        /// `device.v1` protobuf package.
        pub mod v1 {
            include!("generated/device.v1.rs");
        }
    }

    /// `core.v1` protobuf package: the root telemetry `Message`.
    pub mod core {
        /// `core.v1` protobuf package.
        pub mod v1 {
            include!("generated/core.v1.rs");
        }
    }
}

// `core.v1::Message` is not re-exported at the top level: the name would clash
// with the `prost::Message` trait used throughout this module. Reach it via
// [`sensor_message`] (e.g. `protocol::sensor_message::Message`).
pub use generated::crypto::v1::{Encrypted, SignedEnvelope, SignedEnvelopeBatch};
pub use generated::device::v1::{
    EncryptedInsight, EncryptedUrban, Insight, InsightSensor, Urban, UrbanSensor,
};
pub use generated::sensor::v1::{
    Bme280, Bme680, Co2, Gps, Humidity, Ics43434, NoiseLevel, Pm10, Pm25, Pressure, Scd41, Sds011,
    Temperature,
};

/// The root telemetry payload (`core.v1.Message`) carried inside a
/// [`SignedEnvelope`]'s opaque `message` field.
///
/// Re-exported under a dedicated module (rather than at the top level) so the
/// generated `Message` type does not collide with the [`prost::Message`] trait
/// used throughout this module.
pub mod sensor_message {
    pub use crate::protocol::generated::core::v1::{message::Payload, Message, Meta};
}

pub use sp_core::crypto::AccountId32;

use prost::Message;
use rand::RngCore;
use sha2::{Digest, Sha256};
use sp_core::crypto::{Pair as _, Ss58AddressFormat, Ss58Codec};
use sp_core::ed25519::{Pair, Public, Signature};
use std::fmt;
use std::time::{SystemTime, UNIX_EPOCH};

/// Length in bytes of an Ed25519 `sensor_id` (public key).
pub const SENSOR_ID_LEN: usize = 32;
/// Length in bytes of an Ed25519 `signature`.
pub const SIGNATURE_LEN: usize = 64;
/// SS58 network prefix used when presenting a [`SensorId`] as an address.
pub const SENSOR_SS58_PREFIX: u16 = 32;
/// Length in bytes of the random nonce generated by [`sign_message`].
pub const DEFAULT_NONCE_LEN: usize = 16;
/// Minimum accepted `nonce` length (bytes), per the Connectivity Protocol.
pub const MIN_NONCE_LEN: usize = 16;
/// Maximum accepted `nonce` length (bytes), per the Connectivity Protocol.
pub const MAX_NONCE_LEN: usize = 32;

/// Errors produced while decoding, verifying, signing or parsing envelopes.
///
/// The [`ProtocolError::exit_code`] mapping matches the `edge codec` contract:
/// `1` invalid signature, `2` malformed input, `3` local/configuration error.
#[derive(Debug, thiserror::Error)]
pub enum ProtocolError {
    /// The bytes are not a valid `SignedEnvelope` protobuf message.
    #[error("malformed envelope: {0}")]
    Decode(String),
    /// The Ed25519 signature did not verify against the sensor public key.
    #[error("invalid signature")]
    BadSignature,
    /// `sensor_id` is not exactly [`SENSOR_ID_LEN`] bytes.
    #[error("invalid sensor_id length: expected {SENSOR_ID_LEN}, got {0}")]
    SensorIdLen(usize),
    /// `sensor_id` is not a valid Ed25519 public key (not a curve point).
    #[error("invalid sensor_id public key")]
    SensorKey,
    /// `signature` is not exactly [`SIGNATURE_LEN`] bytes.
    #[error("invalid signature length: expected {SIGNATURE_LEN}, got {0}")]
    SignatureLen(usize),
    /// `nonce` is outside the accepted [`MIN_NONCE_LEN`]..=[`MAX_NONCE_LEN`] range.
    #[error("invalid nonce length: expected {MIN_NONCE_LEN}..={MAX_NONCE_LEN}, got {0}")]
    NonceLen(usize),
    /// `message` is empty.
    #[error("empty message")]
    EmptyMessage,
    /// A hex-encoded input could not be parsed.
    #[error("invalid hex: {0}")]
    Hex(String),
}

impl ProtocolError {
    /// Process exit code for the `edge codec` verification commands.
    ///
    /// `1` for an invalid signature, `2` for malformed protocol input, and `3`
    /// for local/configuration errors (e.g. bad hex supplied on the CLI).
    pub fn exit_code(&self) -> i32 {
        match self {
            ProtocolError::BadSignature => 1,
            ProtocolError::Decode(_)
            | ProtocolError::SensorIdLen(_)
            | ProtocolError::SensorKey
            | ProtocolError::SignatureLen(_)
            | ProtocolError::NonceLen(_)
            | ProtocolError::EmptyMessage => 2,
            ProtocolError::Hex(_) => 3,
        }
    }
}

/// Strip the mandatory `0x` prefix from a hex-encoded input, failing if it is
/// absent.
///
/// Every hex string this crate accepts (CLI flags, JSON DTOs, whitelist and
/// key files, ...) must carry an explicit `0x` prefix, matching the
/// convention used throughout the Connectivity Protocol tooling. This keeps
/// hex unambiguous with other accepted encodings (SS58, base64, raw binary)
/// and gives a single, consistent failure mode for malformed input.
pub fn strip_0x(s: &str) -> Result<&str, ProtocolError> {
    s.strip_prefix("0x")
        .ok_or_else(|| ProtocolError::Hex(format!("hex value must be `0x`-prefixed, got: {s}")))
}

/// Ed25519 public key that uniquely identifies a sensor device.
///
/// A `SensorId` is the raw 32-byte Ed25519 public key carried in
/// [`SignedEnvelope::sensor_id`], represented as a Substrate [`AccountId32`] so it
/// renders as an SS58 address and interoperates with the wider Robonomics stack.
/// Authorization decisions are always made against this value, never against
/// transport metadata.
#[derive(Clone, PartialEq, Eq, Hash)]
pub struct SensorId(AccountId32);

impl SensorId {
    /// Borrow the underlying [`AccountId32`].
    pub fn account_id(&self) -> &AccountId32 {
        &self.0
    }

    /// Borrow the raw 32-byte public key.
    pub fn as_bytes(&self) -> &[u8; SENSOR_ID_LEN] {
        AsRef::<[u8; SENSOR_ID_LEN]>::as_ref(&self.0)
    }

    /// Lower-case, `0x`-prefixed hex encoding of the public key.
    pub fn to_hex(&self) -> String {
        format!("0x{}", hex::encode(self.as_bytes()))
    }

    /// Parse a `SensorId` from a `0x`-prefixed hex-encoded 32-byte public key.
    pub fn from_hex(s: &str) -> Result<Self, ProtocolError> {
        let bytes =
            hex::decode(strip_0x(s.trim())?).map_err(|e| ProtocolError::Hex(e.to_string()))?;
        Self::from_slice(&bytes)
    }

    /// SS58 address form of the public key, using [`SENSOR_SS58_PREFIX`].
    pub fn to_ss58(&self) -> String {
        self.0
            .to_ss58check_with_version(Ss58AddressFormat::custom(SENSOR_SS58_PREFIX))
    }

    /// Parse a `SensorId` from its SS58 address form, validating the checksum
    /// and the [`SENSOR_SS58_PREFIX`] network prefix.
    pub fn from_ss58(address: &str) -> Result<Self, ProtocolError> {
        let (account, format) = AccountId32::from_ss58check_with_version(address.trim())
            .map_err(|e| ProtocolError::Hex(format!("invalid ss58 address: {e:?}")))?;
        if format != Ss58AddressFormat::custom(SENSOR_SS58_PREFIX) {
            return Err(ProtocolError::Hex(format!(
                "unexpected ss58 prefix: expected {SENSOR_SS58_PREFIX}, got {format:?}"
            )));
        }
        Ok(Self(account))
    }

    /// Build a `SensorId` from a byte slice, validating its length.
    pub fn from_slice(bytes: &[u8]) -> Result<Self, ProtocolError> {
        let arr: [u8; SENSOR_ID_LEN] = bytes
            .try_into()
            .map_err(|_| ProtocolError::SensorIdLen(bytes.len()))?;
        Ok(Self(AccountId32::new(arr)))
    }
}

impl From<AccountId32> for SensorId {
    fn from(account: AccountId32) -> Self {
        Self(account)
    }
}

impl From<SensorId> for AccountId32 {
    fn from(id: SensorId) -> Self {
        id.0
    }
}

impl fmt::Display for SensorId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_ss58())
    }
}

impl fmt::Debug for SensorId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "SensorId({})", self.to_ss58())
    }
}

/// Content identifier for an encoded envelope: the SHA-256 of its exact bytes.
///
/// The identifier is computed over the raw, as-received envelope bytes (never a
/// re-encoding), so it is stable across the pipeline and is the single value
/// used for both gateway deduplication and the `edge codec id` command.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct EnvelopeId([u8; 32]);

impl EnvelopeId {
    /// Borrow the raw 32-byte digest.
    pub fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    /// Lower-case, `0x`-prefixed hex encoding of the digest.
    pub fn to_hex(&self) -> String {
        format!("0x{}", hex::encode(self.0))
    }
}

impl fmt::Display for EnvelopeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(&self.to_hex())
    }
}

impl fmt::Debug for EnvelopeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "EnvelopeId({})", self.to_hex())
    }
}

/// A [`SignedEnvelope`] whose `sensor_id` and Ed25519 `signature` have been
/// cryptographically verified.
///
/// Producing a `VerifiedEnvelope` is the only supported way to obtain a trusted
/// [`SensorId`] for authorization.
#[derive(Clone, Debug)]
pub struct VerifiedEnvelope {
    /// The validated sensor public key.
    pub sensor_id: SensorId,
    /// The verified envelope.
    pub envelope: SignedEnvelope,
}

/// Options controlling how [`sign_message`] constructs an envelope.
///
/// The measurement timestamp lives in `core.v1.Meta.timestamp` (part of the
/// signed `message` bytes), not the envelope, so it isn't configured here —
/// see `edge message --timestamp`.
#[derive(Clone, Debug, Default)]
pub struct SignOptions {
    /// Explicit anti-replay nonce. A fresh [`DEFAULT_NONCE_LEN`]-byte random
    /// value is generated when `None`.
    pub nonce: Option<Vec<u8>>,
}

/// A sensor's Ed25519 signing identity (private key + derived public key).
#[derive(Clone)]
pub struct SensorIdentity {
    pair: Pair,
}

impl SensorIdentity {
    /// Generate a new random identity from the operating system CSPRNG.
    pub fn generate() -> Self {
        let mut secret = [0u8; SENSOR_ID_LEN];
        rand::rngs::OsRng.fill_bytes(&mut secret);
        Self::from_secret_bytes(&secret)
    }

    /// Construct an identity from a raw 32-byte Ed25519 secret key.
    pub fn from_secret_bytes(secret: &[u8; SENSOR_ID_LEN]) -> Self {
        Self {
            pair: Pair::from_seed(secret),
        }
    }

    /// Parse an identity from a Substrate SURI: a mandatory `0x`-prefixed
    /// 64-digit hex secret seed, or a BIP-39 recovery phrase, optionally
    /// followed by `//hard` / `/soft` derivation junctions and a `///password`.
    /// A hex seed without the `0x` prefix is rejected (interpreted, and
    /// failing, as a BIP-39 phrase). See [`sp_core::crypto::Pair::from_string`]
    /// for the full grammar.
    pub fn from_suri(suri: &str) -> Result<Self, ProtocolError> {
        Pair::from_string(suri.trim(), None)
            .map(|pair| Self { pair })
            .map_err(|e| ProtocolError::Hex(format!("invalid SURI: {e:?}")))
    }

    /// The public [`SensorId`] derived from this identity.
    pub fn sensor_id(&self) -> SensorId {
        SensorId(AccountId32::new(self.pair.public().0))
    }

    /// `0x`-prefixed hex encoding of the raw 32-byte secret key. Handle with care.
    pub fn secret_to_hex(&self) -> String {
        format!("0x{}", hex::encode(self.pair.seed()))
    }
}

impl fmt::Debug for SensorIdentity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        // Never print the secret key material.
        write!(f, "SensorIdentity({})", self.sensor_id())
    }
}

/// Decode a [`SignedEnvelope`] from protobuf wire bytes.
pub fn decode_envelope(bytes: &[u8]) -> Result<SignedEnvelope, ProtocolError> {
    SignedEnvelope::decode(bytes).map_err(|e| ProtocolError::Decode(e.to_string()))
}

/// Encode a [`SignedEnvelope`] to protobuf wire bytes.
///
/// This is intended for constructing *new* envelopes. Never re-encode a received
/// envelope for verification or identification: protobuf serialization is not
/// canonical, so a re-encoding may differ from the signed/original bytes. Use the
/// original bytes with [`envelope_id`] and verify the decoded value in place.
pub fn encode_envelope(envelope: &SignedEnvelope) -> Vec<u8> {
    envelope.encode_to_vec()
}

/// Compute the [`EnvelopeId`] (SHA-256) over the exact encoded envelope bytes.
pub fn envelope_id(bytes: &[u8]) -> EnvelopeId {
    let digest = Sha256::digest(bytes);
    EnvelopeId(digest.into())
}

/// Decode a `core.v1.Message` (the complete sensor telemetry payload) from
/// protobuf wire bytes, i.e. the bytes carried in a [`SignedEnvelope::message`]
/// field.
pub fn decode_sensor_message(bytes: &[u8]) -> Result<sensor_message::Message, ProtocolError> {
    sensor_message::Message::decode(bytes).map_err(|e| ProtocolError::Decode(e.to_string()))
}

/// Encode a `core.v1.Message` (the complete sensor telemetry payload) to
/// protobuf wire bytes, ready to place in a [`SignedEnvelope::message`] field.
pub fn encode_sensor_message(message: &sensor_message::Message) -> Vec<u8> {
    message.encode_to_vec()
}

/// Canonical byte string that the Ed25519 `signature` covers.
///
/// Layout: `sensor_id || nonce || message`. The measurement timestamp is no
/// longer part of the envelope (Connectivity Protocol v1-beta.2); it now
/// lives in `core.v1.Meta.timestamp`, inside the serialized `message` bytes,
/// so it remains cryptographically covered without a dedicated field here.
///
/// This matches the authoritative reference implementation in
/// `airalab/connectivity-cloud` (`packages/core/src/utils.ts`,
/// `buildEnvelopeSigningBytes`). It is the single place that defines the
/// signed layout.
fn signing_payload(envelope: &SignedEnvelope) -> Vec<u8> {
    let mut buf = Vec::with_capacity(
        envelope.sensor_id.len() + envelope.nonce.len() + envelope.message.len(),
    );
    buf.extend_from_slice(&envelope.sensor_id);
    buf.extend_from_slice(&envelope.nonce);
    buf.extend_from_slice(&envelope.message);
    buf
}

/// Validate the structural invariants of a decoded [`SignedEnvelope`], mirroring
/// `validateSignedEnvelope` in `airalab/connectivity-cloud`: `sensor_id` and
/// `signature` lengths, the accepted `nonce` range, and a non-empty `message`.
///
/// Returns the parsed [`SensorId`] on success. This does **not** check the
/// signature; see [`verify_envelope`].
pub fn validate_envelope(envelope: &SignedEnvelope) -> Result<SensorId, ProtocolError> {
    let sensor_id = SensorId::from_slice(&envelope.sensor_id)?;
    if envelope.signature.len() != SIGNATURE_LEN {
        return Err(ProtocolError::SignatureLen(envelope.signature.len()));
    }
    if envelope.nonce.len() < MIN_NONCE_LEN || envelope.nonce.len() > MAX_NONCE_LEN {
        return Err(ProtocolError::NonceLen(envelope.nonce.len()));
    }
    if envelope.message.is_empty() {
        return Err(ProtocolError::EmptyMessage);
    }
    Ok(sensor_id)
}

/// Verify the Ed25519 signature of a decoded [`SignedEnvelope`].
///
/// Structural invariants are checked first (see [`validate_envelope`]), then the
/// signature is verified over [`signing_payload`]. On success the returned
/// [`VerifiedEnvelope`] carries the validated [`SensorId`]. The envelope is
/// verified in place; its bytes are never re-encoded (see [`encode_envelope`]).
pub fn verify_envelope(envelope: &SignedEnvelope) -> Result<VerifiedEnvelope, ProtocolError> {
    let sensor_id = validate_envelope(envelope)?;
    let public = Public::from_raw(*sensor_id.as_bytes());

    let sig_bytes: [u8; SIGNATURE_LEN] = envelope
        .signature
        .as_slice()
        .try_into()
        .map_err(|_| ProtocolError::SignatureLen(envelope.signature.len()))?;
    let signature = Signature::from_raw(sig_bytes);

    if !Pair::verify(&signature, signing_payload(envelope), &public) {
        return Err(ProtocolError::BadSignature);
    }

    Ok(VerifiedEnvelope {
        sensor_id,
        envelope: envelope.clone(),
    })
}

/// Sign a telemetry `message` with the given [`SensorIdentity`], producing a
/// [`SignedEnvelope`] that [`verify_envelope`] will accept.
pub fn sign_message(
    identity: &SensorIdentity,
    message: &[u8],
    options: SignOptions,
) -> SignedEnvelope {
    let nonce = options.nonce.unwrap_or_else(|| {
        let mut n = vec![0u8; DEFAULT_NONCE_LEN];
        rand::rngs::OsRng.fill_bytes(&mut n);
        n
    });

    let mut envelope = SignedEnvelope {
        sensor_id: identity.sensor_id().as_bytes().to_vec(),
        nonce,
        message: message.to_vec(),
        signature: Vec::new(),
    };

    let signature = identity.pair.sign(&signing_payload(&envelope));
    envelope.signature = signature.0.to_vec();
    envelope
}

/// Current Unix time in milliseconds (UTC), saturating at the epoch.
pub fn now_unix_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn identity() -> SensorIdentity {
        SensorIdentity::from_secret_bytes(&[7u8; SENSOR_ID_LEN])
    }

    #[test]
    fn sign_then_verify_round_trip() {
        let id = identity();
        let envelope = sign_message(&id, b"telemetry", SignOptions::default());
        let verified = verify_envelope(&envelope).expect("valid signature");
        assert_eq!(verified.sensor_id, id.sensor_id());
        assert_eq!(envelope.signature.len(), SIGNATURE_LEN);
        assert_eq!(envelope.nonce.len(), DEFAULT_NONCE_LEN);
    }

    #[test]
    fn decode_encode_round_trip() {
        let id = identity();
        let envelope = sign_message(&id, b"payload", SignOptions::default());
        let bytes = encode_envelope(&envelope);
        let decoded = decode_envelope(&bytes).expect("decodes");
        assert_eq!(decoded, envelope);
    }

    #[test]
    fn tampered_message_is_rejected() {
        let id = identity();
        let mut envelope = sign_message(&id, b"telemetry", SignOptions::default());
        envelope.message = b"tampered".to_vec();
        assert!(matches!(
            verify_envelope(&envelope),
            Err(ProtocolError::BadSignature)
        ));
    }

    #[test]
    fn wrong_signer_is_rejected() {
        let envelope = sign_message(&identity(), b"telemetry", SignOptions::default());
        let mut forged = envelope.clone();
        // Replace sensor_id with a different key; signature no longer matches.
        forged.sensor_id = SensorIdentity::from_secret_bytes(&[9u8; SENSOR_ID_LEN])
            .sensor_id()
            .as_bytes()
            .to_vec();
        assert!(verify_envelope(&forged).is_err());
    }

    #[test]
    fn bad_lengths_are_reported() {
        let mut envelope = sign_message(&identity(), b"x", SignOptions::default());
        envelope.sensor_id.truncate(10);
        assert!(matches!(
            verify_envelope(&envelope),
            Err(ProtocolError::SensorIdLen(10))
        ));

        let mut envelope = sign_message(&identity(), b"x", SignOptions::default());
        envelope.signature.truncate(3);
        assert!(matches!(
            verify_envelope(&envelope),
            Err(ProtocolError::SignatureLen(3))
        ));
    }

    #[test]
    fn envelope_id_is_stable_over_exact_bytes() {
        let envelope = sign_message(&identity(), b"telemetry", SignOptions::default());
        let bytes = encode_envelope(&envelope);
        assert_eq!(envelope_id(&bytes), envelope_id(&bytes));
        // A single flipped byte changes the identifier.
        let mut altered = bytes.clone();
        altered[0] ^= 0xff;
        assert_ne!(envelope_id(&bytes), envelope_id(&altered));
    }

    #[test]
    fn sensor_id_hex_round_trip() {
        let id = identity().sensor_id();
        let parsed = SensorId::from_hex(&id.to_hex()).expect("valid hex");
        assert_eq!(id, parsed);
    }

    #[test]
    fn sensor_id_ss58_round_trip() {
        let id = identity().sensor_id();
        let address = id.to_ss58();
        let parsed = SensorId::from_ss58(&address).expect("valid ss58");
        assert_eq!(id, parsed);
    }

    #[test]
    fn sensor_id_ss58_uses_expected_prefix() {
        // Well-known Substrate "Alice" public key. Encoding it with the
        // Connectivity Protocol prefix (32) must round-trip, and decoding the
        // same key under the default prefix (42) must be rejected.
        let pubkey =
            hex::decode("d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d")
                .unwrap();
        let id = SensorId::from_slice(&pubkey).unwrap();
        let address = id.to_ss58();
        assert_eq!(SensorId::from_ss58(&address).unwrap(), id);

        let default_prefix = AccountId32::new(pubkey.try_into().unwrap()).to_ss58check();
        assert!(SensorId::from_ss58(&default_prefix).is_err());
    }

    #[test]
    fn error_exit_codes_match_codec_contract() {
        assert_eq!(ProtocolError::BadSignature.exit_code(), 1);
        assert_eq!(ProtocolError::SensorIdLen(1).exit_code(), 2);
        assert_eq!(ProtocolError::Decode(String::new()).exit_code(), 2);
        assert_eq!(ProtocolError::NonceLen(1).exit_code(), 2);
        assert_eq!(ProtocolError::EmptyMessage.exit_code(), 2);
        assert_eq!(ProtocolError::Hex(String::new()).exit_code(), 3);
    }

    #[test]
    fn signing_payload_matches_sensor_id_nonce_message_layout() {
        // Locks the wire layout against `airalab/connectivity-cloud`
        // (`buildEnvelopeSigningBytes`). Connectivity Protocol v1-beta.2
        // dropped the envelope-level timestamp, so the signed payload is now
        // just `sensor_id || nonce || message`.
        let envelope = SignedEnvelope {
            sensor_id: vec![1u8; SENSOR_ID_LEN],
            nonce: vec![2u8; MIN_NONCE_LEN],
            message: vec![3u8; 4],
            signature: Vec::new(),
        };
        let mut expected = Vec::new();
        expected.extend_from_slice(&[1u8; SENSOR_ID_LEN]);
        expected.extend_from_slice(&[2u8; MIN_NONCE_LEN]);
        expected.extend_from_slice(&[3u8; 4]);
        assert_eq!(signing_payload(&envelope), expected);
    }

    #[test]
    fn nonce_out_of_range_is_rejected() {
        let id = identity();
        let mut short = sign_message(&id, b"telemetry", SignOptions::default());
        short.nonce = vec![0u8; MIN_NONCE_LEN - 1];
        assert!(matches!(
            verify_envelope(&short),
            Err(ProtocolError::NonceLen(_))
        ));

        let mut long = sign_message(&id, b"telemetry", SignOptions::default());
        long.nonce = vec![0u8; MAX_NONCE_LEN + 1];
        assert!(matches!(
            verify_envelope(&long),
            Err(ProtocolError::NonceLen(_))
        ));
    }

    #[test]
    fn empty_message_is_rejected() {
        let mut envelope = sign_message(&identity(), b"telemetry", SignOptions::default());
        envelope.message.clear();
        assert!(matches!(
            verify_envelope(&envelope),
            Err(ProtocolError::EmptyMessage)
        ));
    }
}
